package com.loftcat.weibo.vo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT_VO.
 */
public class AccountVo implements Vo{

    private Long id;
    private String uid;
    private String userInfo;
    private String token;
    private String expires_in;
    private String name;

    public AccountVo() {
    }

    public AccountVo(Long id) {
        this.id = id;
    }

    public AccountVo(Long id, String uid, String userInfo, String token, String expires_in, String name) {
        this.id = id;
        this.uid = uid;
        this.userInfo = userInfo;
        this.token = token;
        this.expires_in = expires_in;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getExpires_in() {
        return expires_in;
    }

    public void setExpires_in(String expires_in) {
        this.expires_in = expires_in;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
