package com.loftcat.weibo.vo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKGROUND_VO.
 */
public class BackgroundVo implements Vo{

    private Integer smallImage;
    private Integer largeImage;

    public BackgroundVo() {
    }

    public BackgroundVo(Integer smallImage, Integer largeImage) {
        this.smallImage = smallImage;
        this.largeImage = largeImage;
    }

    public Integer getSmallImage() {
        return smallImage;
    }

    public void setSmallImage(Integer smallImage) {
        this.smallImage = smallImage;
    }

    public Integer getLargeImage() {
        return largeImage;
    }

    public void setLargeImage(Integer largeImage) {
        this.largeImage = largeImage;
    }

}
