package com.loftcat.weibo.vo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.loftcat.weibo.vo.AccountVo;
import com.loftcat.weibo.vo.BackgroundVo;
import com.loftcat.weibo.vo.UserVO;

import com.loftcat.weibo.vo.AccountVoDao;
import com.loftcat.weibo.vo.BackgroundVoDao;
import com.loftcat.weibo.vo.UserVODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountVoDaoConfig;
    private final DaoConfig backgroundVoDaoConfig;
    private final DaoConfig userVODaoConfig;

    private final AccountVoDao accountVoDao;
    private final BackgroundVoDao backgroundVoDao;
    private final UserVODao userVODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountVoDaoConfig = daoConfigMap.get(AccountVoDao.class).clone();
        accountVoDaoConfig.initIdentityScope(type);

        backgroundVoDaoConfig = daoConfigMap.get(BackgroundVoDao.class).clone();
        backgroundVoDaoConfig.initIdentityScope(type);

        userVODaoConfig = daoConfigMap.get(UserVODao.class).clone();
        userVODaoConfig.initIdentityScope(type);

        accountVoDao = new AccountVoDao(accountVoDaoConfig, this);
        backgroundVoDao = new BackgroundVoDao(backgroundVoDaoConfig, this);
        userVODao = new UserVODao(userVODaoConfig, this);

        registerDao(AccountVo.class, accountVoDao);
        registerDao(BackgroundVo.class, backgroundVoDao);
        registerDao(UserVO.class, userVODao);
    }
    
    public void clear() {
        accountVoDaoConfig.getIdentityScope().clear();
        backgroundVoDaoConfig.getIdentityScope().clear();
        userVODaoConfig.getIdentityScope().clear();
    }

    public AccountVoDao getAccountVoDao() {
        return accountVoDao;
    }

    public BackgroundVoDao getBackgroundVoDao() {
        return backgroundVoDao;
    }

    public UserVODao getUserVODao() {
        return userVODao;
    }

}
